### ISSUE TITLE
No such file or directory on the Server

### ISSUE THREAD

**Issue by Jiasen** [batra-mlp-lab/pcloudcv#26]
Traceback (most recent call last):
  File "./app/views.py", line 313, in matlabReadRequest
    response = saveFilesAndProcess(request, job_obj)
  File "./app/savefile.py", line 88, in saveFilesAndProcess
    os.mkdir(job_obj.storage_path)
OSError: [Errno 2] No such file or directory: '/srv/share/cloudcv/jobs/d2ec6786-d42e-11e4-b35f-22000aef83c4/'

**Comment by Jiasen** [comment]
The whole log is here

Executable Params: {u'server': u'decaf_server', u'name': u'decaf', u'verbose': u'2'}

SocketID:  NMyaU_gOyzSX4ZT7SM1K
Starting The POST request

Server: Post Request Recieved

Info:   Please wait while CloudCV runs your job request

Traceback (most recent call last):
  File "./app/views.py", line 313, in matlabReadRequest
    response = saveFilesAndProcess(request, job_obj)
  File "./app/savefile.py", line 88, in saveFilesAndProcess
    os.mkdir(job_obj.storage_path)
OSError: [Errno 2] No such file or directory: '/srv/share/cloudcv/jobs/d2ec6786-d42e-11e4-b35f-22000aef83c4/'


Exiting From the Post Request Thread

Exiting Redis Thread for HTTP Post requests

Lost connection (Connection closed)
Ending Listing to Redis Channel

Socket waiting finished. 

Exiting Socket Connection Thread

**Comment by dexter1691** [comment]
The decaf_server functionality is not currently working. We switched to a new server and its on to-fix list. Thanks for reporting. I will mark it as solved when it's working again
